error = {
    "400": "Token no reconocido",
    "401": "Símbolo después de cierre",
    "402": "Cadena no cerrada",
    "500": "Inicio de expresión ilegal",
    "501": "Programa incompleto, se esperaba begin",
    "502": "Programa incompleto, se esperaba end",
    "503": "Programa incompleto, se esperaba nombre del programa",
    "504": "Error de sintaxis, se esperaba ;",
    "505": "Error de sintaxis, se esperaba if",
    "506": "Error de sintaxis, se esperaba during",
    "507": "Error de sintaxis, se esperaba do",
    "508": "Error de sintaxis, se esperaba fun",
    "509": "Error de sintaxis, se esperaba back",
    "510": "No existe programa con el formato esperado",
    "511": "Error de sintaxis, se esperaba un nombre de función",
    "512": "Elemento suelto",
    "513": "Error de sintaxis, se esperaba out",
    "514": "Error de sintaxis, se esperaba in",
    "515": "Error de sintaxis, se esperaba tipo de dato",
    "516": "Error de sintaxis, se esperaba but",
    "517": "Error de sintaxis, se esperaba {",
    "518": "Error de sintaxis, se esperaba }",
"519": "Programa incompleto, se encontró final pero no inicio",
    "520": "Programa incompleto, se encontró inicio pero no final",
    "600": "Variable con valor invalído",
    "601": "Variable no declarada",
    "602": "Variable fuera de ámbito",
    "603": "División entre cero"
}